version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - server
    ports:
      - "127.0.0.1:9091:3000"
    networks:
      - holloway
    restart: always
  server:
    container_name: prometheus-server
    command: "--config.file=/etc/prometheus/prometheus.yml"
    image: prom/prometheus
    networks:
      - holloway
    ports:
      - "127.0.0.1:9090:9090"
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  exporter:
    container_name: node-exporter
    image: prom/node-exporter
    networks:
      - holloway
    ports:
      - "127.0.0.1:9100:9100"
    restart: always
networks:
  holloway:
    external:
      name: holloway_net
